# Generated by Django 2.2 on 2020-03-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200301_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='GEG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=50)),
                ('last', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('number', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('birth', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('people', models.ManyToManyField(blank=True, null=True, to='api.Person')),
            ],
        ),
    ]
