# Generated by Django 2.2 on 2020-03-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_geg'),
    ]

    operations = [
        migrations.AddField(
            model_name='geg',
            name='color_code',
            field=models.CharField(default='102542', max_length=6),
            preserve_default=False,
        ),
    ]
