# Generated by Django 2.2 on 2020-03-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_geg_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geg',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geg',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
